### ISSUE TITLE
key and title did not work as expected

### ISSUE THREAD

**Issue by KeithPinson** [superspacehero/giticon#1]
```
$ ./commit.sh --dry-run doc "Add a markdown file"
Optional scope (e.g. Android):
This commit will...(e.g. Let swipe go all the way to bottom): 
```

Quoted string should be assumed to be the commit message

Note: Maybe -m "message" should also work like with git:
`git commit -m "message"`

**Comment by KeithPinson** [comment]
Should add that prompt for optional scope should be dropped if _commit type_ and _message_ are provided.

**Comment by superspacehero** [comment]
Message and scope can now be specified using -m "message" and -s "scope". Am looking into trying to do this as you describe, as well.
